//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vactination_DB_Manager {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GridViewLangMasks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridViewLangMasks() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vactination_DB_Manager.GridViewLangMasks", typeof(GridViewLangMasks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на temp immunization id,
        ///legal entity id,
        ///division identifier value,
        ///status,
        ///not given,
        ///vaccine code,
        ///immunization date,
        ///patient age group,
        ///patient gender,
        ///manufacturer,
        ///lot number,
        ///expiration date,
        ///dose quantity unit,
        ///dose quantity value,
        ///vaccination protocol dose sequence,
        ///vaccination protocol series,
        ///vaccination protocol series doses,
        ///vaccination protocol target diseases,
        ///inserted at,
        ///updated at.
        /// </summary>
        public static string EN_lang_grid_mask {
            get {
                return ResourceManager.GetString("EN_lang_grid_mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;ID тимчасової імунізації&quot;,
        ///&quot;ID юридичної особи&quot;,
        ///&quot;ID Закладу&quot;,
        ///&quot;Статус&quot;,
        ///&quot;Не надано&quot;,
        ///&quot;Код вакцини&quot;,
        ///&quot;Дата імунізації&quot;,
        ///&quot;Вікова група&quot;,
        ///&quot;Стать&quot;,
        ///&quot;Виробник&quot;,
        ///&quot;Номер партії&quot;,
        ///&quot;Придатна до&quot;,
        ///&quot;Одиниці виміру дози&quot;,
        ///&quot;Значення&quot;,
        ///&quot;Послідовність доз вакцинаційного протоколу&quot;,
        ///&quot;Серія вакцинаційного протоколу&quot;,
        ///&quot;Дози серії вакцинаційного протоколу&quot;,
        ///&quot;Цільові захворювання&quot;,
        ///&quot;Вставлено в&quot;,
        ///&quot;Оновлено в&quot;.
        /// </summary>
        public static string UA_lang_grid_mask {
            get {
                return ResourceManager.GetString("UA_lang_grid_mask", resourceCulture);
            }
        }
    }
}
